<?php
/**
 * Echo Prayer Settings
 *
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 * 
 * @package   Echo
 * @author 	  Kaleb Heitzman <kalebheitzman@gmail.com>
 * @link      https://github.com/kalebheitzman/echo
 * @copyright 2015 Kaleb Heitzman
 * @license   GPL-3.0
 * @version   0.9.0
 */

class EchoSettings {

	private $echo_settings_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'echo_settings_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'echo_settings_page_init' ) );

		add_action( 'admin_menu' , array( $this, 'echo_prayer_feeds_page' ) );

	}

	/**
	 * Build Feeds Menu
	 * @return hook
	 * @since  0.9.0
	 */
	public function echo_prayer_feeds_page() {
		add_submenu_page('echo-settings', 'Feeds', 'Feeds', 'edit_posts', 'echo-feeds', array( $this, 'echo_prayer_feeds_page_cb') );
	}

	public function echo_settings_add_plugin_page() {
		add_menu_page(
			'Echo Prayer Settings', // page_title
			'Echo', // menu_title
			'manage_options', // capability
			'echo-settings', // menu_slug
			array( $this, 'echo_settings_create_admin_page' ), // function
			'dashicons-heart', // icon_url
			81 // position
		);
	}

	public function echo_settings_create_admin_page() {
		$this->echo_settings_options = get_option( 'echo_settings_option_name' ); ?>

		<div class="wrap">
			<h2>Echo Prayer Settings</h2>
			<p>Echo Prayer Settings</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'echo_settings_option_group' );
					do_settings_sections( 'echo-settings-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function echo_settings_page_init() {
		register_setting(
			'echo_settings_option_group', // option_group
			'echo_settings_option_name', // option_name
			array( $this, 'echo_settings_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'echo_settings_setting_section', // id
			'Settings', // title
			array( $this, 'echo_settings_section_info' ), // callback
			'echo-settings-admin' // page
		);

		add_settings_field(
			'notification_email_0', // id
			'Notification Email', // title
			array( $this, 'notification_email_0_callback' ), // callback
			'echo-settings-admin', // page
			'echo_settings_setting_section' // section
		);

		add_settings_field(
			'prayer_form_response_7', // id
			'Prayer Form Response', // title
			array( $this, 'prayer_form_response_7_callback' ), // callback
			'echo-settings-admin', // page
			'echo_settings_setting_section' // section
		);

		add_settings_field(
			'mailchimp_api_key_1', // id
			'MailChimp API Key', // title
			array( $this, 'mailchimp_api_key_1_callback' ), // callback
			'echo-settings-admin', // page
			'echo_settings_setting_section' // section
		);

		add_settings_field(
			'primary_color_2', // id
			'Primary Color', // title
			array( $this, 'primary_color_2_callback' ), // callback
			'echo-settings-admin', // page
			'echo_settings_setting_section' // section
		);

		add_settings_field(
			'secondary_color_3', // id
			'Secondary Color', // title
			array( $this, 'secondary_color_3_callback' ), // callback
			'echo-settings-admin', // page
			'echo_settings_setting_section' // section
		);

		add_settings_field(
			'categories_enabled_4', // id
			'Categories Enabled', // title
			array( $this, 'categories_enabled_4_callback' ), // callback
			'echo-settings-admin', // page
			'echo_settings_setting_section' // section
		);

		add_settings_field(
			'tags_enabled_5', // id
			'Tags Enabled', // title
			array( $this, 'tags_enabled_5_callback' ), // callback
			'echo-settings-admin', // page
			'echo_settings_setting_section' // section
		);

		/*add_settings_field(
			'default_category_6', // id
			'Default Category', // title
			array( $this, 'default_category_6_callback' ), // callback
			'echo-settings-admin', // page
			'echo_settings_setting_section' // section
		);*/

		/*add_settings_field(
			'example_radio_8', // id
			'Example Radio', // title
			array( $this, 'example_radio_8_callback' ), // callback
			'echo-settings-admin', // page
			'echo_settings_setting_section' // section
		);*/
	}

	public function echo_settings_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['notification_email_0'] ) ) {
			$sanitary_values['notification_email_0'] = sanitize_text_field( $input['notification_email_0'] );
		}

		if ( isset( $input['mailchimp_api_key_1'] ) ) {
			$sanitary_values['mailchimp_api_key_1'] = sanitize_text_field( $input['mailchimp_api_key_1'] );
		}

		if ( isset( $input['primary_color_2'] ) ) {
			$sanitary_values['primary_color_2'] = sanitize_text_field( $input['primary_color_2'] );
		}

		if ( isset( $input['secondary_color_3'] ) ) {
			$sanitary_values['secondary_color_3'] = sanitize_text_field( $input['secondary_color_3'] );
		}

		if ( isset( $input['categories_enabled_4'] ) ) {
			$sanitary_values['categories_enabled_4'] = $input['categories_enabled_4'];
		}

		if ( isset( $input['tags_enabled_5'] ) ) {
			$sanitary_values['tags_enabled_5'] = $input['tags_enabled_5'];
		}

		if ( isset( $input['default_category_6'] ) ) {
			$sanitary_values['default_category_6'] = $input['default_category_6'];
		}

		if ( isset( $input['prayer_form_response_7'] ) ) {
			$sanitary_values['prayer_form_response_7'] = esc_textarea( $input['prayer_form_response_7'] );
		}

		if ( isset( $input['example_radio_8'] ) ) {
			$sanitary_values['example_radio_8'] = $input['example_radio_8'];
		}

		return $sanitary_values;
	}

	public function echo_settings_section_info() {
		
	}

	public function notification_email_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="echo_settings_option_name[notification_email_0]" id="notification_email_0" value="%s" placeholder="prayer@example.com">',
			isset( $this->echo_settings_options['notification_email_0'] ) ? esc_attr( $this->echo_settings_options['notification_email_0']) : ''
		);
	}

	public function mailchimp_api_key_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="echo_settings_option_name[mailchimp_api_key_1]" id="mailchimp_api_key_1" value="%s">',
			isset( $this->echo_settings_options['mailchimp_api_key_1'] ) ? esc_attr( $this->echo_settings_options['mailchimp_api_key_1']) : ''
		);
	}

	public function primary_color_2_callback() {
		printf(
			'<input class="regular-text color-field" type="text" name="echo_settings_option_name[primary_color_2]" id="primary_color_2" value="%s">',
			isset( $this->echo_settings_options['primary_color_2'] ) ? esc_attr( $this->echo_settings_options['primary_color_2']) : ''
		);
	}

	public function secondary_color_3_callback() {
		printf(
			'<input class="regular-text color-field" type="text" name="echo_settings_option_name[secondary_color_3]" id="secondary_color_3" value="%s">',
			isset( $this->echo_settings_options['secondary_color_3'] ) ? esc_attr( $this->echo_settings_options['secondary_color_3']) : ''
		);
	}

	public function categories_enabled_4_callback() {
		?> <fieldset><?php $checked = ( isset( $this->echo_settings_options['categories_enabled_4'] ) && $this->echo_settings_options['categories_enabled_4'] === '1' ) ? 'checked' : '' ; ?>
		<label for="categories_enabled_4-0"><input type="radio" name="echo_settings_option_name[categories_enabled_4]" id="categories_enabled_4-0" value="1" <?php echo $checked; ?>> Yes</label><br>
		<?php $checked = ( isset( $this->echo_settings_options['categories_enabled_4'] ) && $this->echo_settings_options['categories_enabled_4'] === '0' ) ? 'checked' : '' ; ?>
		<label for="categories_enabled_4-1"><input type="radio" name="echo_settings_option_name[categories_enabled_4]" id="categories_enabled_4-1" value="0" <?php echo $checked; ?>> No</label></fieldset> <?php
	}

	public function tags_enabled_5_callback() {
		?> <fieldset><?php $checked = ( isset( $this->echo_settings_options['tags_enabled_5'] ) && $this->echo_settings_options['tags_enabled_5'] === '1' ) ? 'checked' : '' ; ?>
		<label for="tags_enabled_5-0"><input type="radio" name="echo_settings_option_name[tags_enabled_5]" id="tags_enabled_5-0" value="1" <?php echo $checked; ?>> Yes</label><br>
		<?php $checked = ( isset( $this->echo_settings_options['tags_enabled_5'] ) && $this->echo_settings_options['tags_enabled_5'] === '0' ) ? 'checked' : '' ; ?>
		<label for="tags_enabled_5-1"><input type="radio" name="echo_settings_option_name[tags_enabled_5]" id="tags_enabled_5-1" value="0" <?php echo $checked; ?>> No</label></fieldset> <?php
	}

	public function default_category_6_callback() {
		?> <select name="echo_settings_option_name[default_category_6]" id="default_category_6">
			<?php $selected = (isset( $this->echo_settings_options['default_category_6'] ) && $this->echo_settings_options['default_category_6'] === '1') ? 'selected' : '' ; ?>
			<option value="1" <?php echo $selected; ?>>Yes</option>
			<?php $selected = (isset( $this->echo_settings_options['default_category_6'] ) && $this->echo_settings_options['default_category_6'] === '0') ? 'selected' : '' ; ?>
			<option value="0" <?php echo $selected; ?>>No</option>
		</select> <?php
	}

	public function prayer_form_response_7_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="echo_settings_option_name[prayer_form_response_7]" id="prayer_form_response_7" placeholder="Thanks for submitting your prayer request.">%s</textarea>',
			isset( $this->echo_settings_options['prayer_form_response_7'] ) ? esc_attr( $this->echo_settings_options['prayer_form_response_7']) : ''
		);
	}

	public function example_radio_8_callback() {
		?> <fieldset><?php $checked = ( isset( $this->echo_settings_options['example_radio_8'] ) && $this->echo_settings_options['example_radio_8'] === '1' ) ? 'checked' : '' ; ?>
		<label for="example_radio_8-0"><input type="radio" name="echo_settings_option_name[example_radio_8]" id="example_radio_8-0" value="1" <?php echo $checked; ?>> Yes</label><br>
		<?php $checked = ( isset( $this->echo_settings_options['example_radio_8'] ) && $this->echo_settings_options['example_radio_8'] === '0' ) ? 'checked' : '' ; ?>
		<label for="example_radio_8-1"><input type="radio" name="echo_settings_option_name[example_radio_8]" id="example_radio_8-1" value="0" <?php echo $checked; ?>> No</label></fieldset> <?php
	}

	/**
	 * Build the Feeds Page
	 *
	 * This is a callback for prayer_feeds_menu. It generates html to be
	 * displayed on this submenu page.
	 * 
	 * @return html
	 * @since  0.9.0
	 */
	function echo_prayer_feeds_page_cb() {
		$templates = new Echo_Template_Loader;
		// start a buffer to capture output
		$output = $templates->get_template_part( 'admin', 'feeds' );
	}

}
if ( is_admin() )
	$echo_settings = new EchoSettings();

/* 
 * Retrieve this value with:
 * $echo_settings_options = get_option( 'echo_settings_option_name' ); // Array of All Options
 * $notification_email_0 = $echo_settings_options['notification_email_0']; // Notification Email
 * $mailchimp_api_key_1 = $echo_settings_options['mailchimp_api_key_1']; // MailChimp API Key
 * $primary_color_2 = $echo_settings_options['primary_color_2']; // Primary Color
 * $secondary_color_3 = $echo_settings_options['secondary_color_3']; // Secondary Color
 * $categories_enabled_4 = $echo_settings_options['categories_enabled_4']; // Categories Enabled
 * $tags_enabled_5 = $echo_settings_options['tags_enabled_5']; // Tags Enabled
 * $default_category_6 = $echo_settings_options['default_category_6']; // Default Category
 * $prayer_form_response_7 = $echo_settings_options['prayer_form_response_7']; // Example Textarea
 * $example_radio_8 = $echo_settings_options['example_radio_8']; // Example Radio
 */

